name:                baseDAO
version:             0.1.0.0
license:             MIT
author:              Serokell, Tocqueville Group
copyright:           2020 TQ Tezos

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/tqtezos/baseDAO#readme>

dependencies:
  - base >= 4.7 && < 5
  - universum
  - morley == 1.6.0
  - lorentz == 0.6.0

library:
  source-dirs: src

executables:
  baseDAO:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - baseDAO

tests:
  baseDAO-test:
    main:                Spec.hs
    source-dirs:         test
    build-tools: tasty-discover:tasty-discover

    ghc-options:
    - -threaded
    - -rtsopts
    - -eventlog
    - -with-rtsopts=-N
    - '"-with-rtsopts=-N -A64m -AL256m"'

    dependencies:
    - baseDAO
