# SPDX-FileCopyrightText: 2020 TQ Tezos
# SPDX-License-Identifier: LicenseRef-MIT-TQ

resolver: template/snapshot.yaml

packages:
  - .
  - template
  - ligo/test

# See extra-deps in template/snapshot.yaml
