# SPDX-FileCopyrightText: 2020 TQ Tezos
# SPDX-License-Identifier: LicenseRef-MIT-TQ

env:
  TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"
  # this key is defined in local-chain bootstrap accounts list in
  # https://github.com/serokell/serokell-profiles/blob/master/profiles/servers/jupiter/default.nix
  TASTY_NETTEST_IMPORT_SECRET_KEY: "unencrypted:edsk3nAQ3uCP7vc2ccLhhWNNncgFfWQ5HgTyPawepQ8DURRRfzVQzB"

steps:
  - label: hlint
    if: &not_scheduled
     build.source != "schedule"
    commands:
    - nix run -f ci.nix pkgs.hlint -c
        ./scripts/lint.sh

  - label: reuse lint
    if: *not_scheduled
    commands:
    - nix run -f ci.nix pkgs.reuse -c
        reuse lint

  - label: check trailing whitespace
    if: *not_scheduled
    commands:
    - .buildkite/check-trailing-whitespace.sh

  - label: xrefcheck
    if: *not_scheduled
    commands:
    - nix run -f ci.nix xrefcheck -c xrefcheck
    retry:
      automatic:
        limit: 1

  - label: check cabal files
    if: *not_scheduled
    commands:
    - nix run -f ci.nix stack2cabal pkgs.diffutils -c ./scripts/ci/validate-cabal-files.sh

  - label: build-ligo
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A build-ligo -o baseDAO-non-optimized.tz
    - nix run -f ci.nix morley -c morley optimize --contract baseDAO-non-optimized.tz --output baseDAO.tz
    artifact_paths:
      - baseDAO.tz

  - label: build-haskell
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A all-components

  - label: bats
    if: *not_scheduled
    commands:
    - nix run -f ci.nix
          tezos-client
          pkgs.bats
          packages.baseDAO.exes.baseDAO
          packages.baseDAO-ligo-meta.exes.baseDAO-ligo-meta
        -c bats ./scripts/test.bats

  - label: test
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A packages.baseDAO.tests.baseDAO-test
    # Emulator + local chain for Delphi protocol
    - nix run -f ci.nix tezos-client -c
      ./result/bin/baseDAO-test --nettest-run-network
      -A localhost -P 8735

  - label: ligo-test
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A packages.baseDAO-ligo-meta.tests.baseDAO-test
    # Running only on emulator for now due to oversized operations
    - nix run -f ci.nix tezos-client -c
      ./result/bin/baseDAO-test --nettest-no-run-network
      -A localhost -P 8735

  - label: weeder
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A weeder-script
      # weeder needs .cabal file:
    - nix run -f ci.nix pkgs.haskellPackages.hpack -c hpack
    - ./result

  - label: haddock
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A haddock --no-out-link

  - label: scheduled delphinet test
    if: build.source == "schedule"
    # use another agent for long scheduled jobs
    agents:
      queue: "scheduled"
    commands:
    - nix-build ci.nix -A packages.baseDAO.tests.baseDAO-test
    # Emulator + testnet for Delphi protocol
    - nix run -f ci.nix tezos-client -c
      ./result/bin/baseDAO-test --nettest-run-network
      -A delphi.testnet.tezos.serokell.team -P 8732
    retry:
      automatic:
        limit: 1
    timeout_in_minutes: 150

# Autodoc
  - label: contract doc development
    if: build.branch != "autodoc/master" && build.branch != "master" && build.source != "schedule"
    commands:
    - nix-build ci.nix -A contracts-doc --arg release false
    - ln -s ./result/*.md .
    artifact_paths:
      - TrivialDAO.md
      - GameDAO.md
      - RegistryDAO.md
      - TreasuryDAO.md

  - label: contract doc release
    if: build.branch == "master" && build.source != "schedule"
    commands:
    - nix-build ci.nix -A contracts-doc --arg release true
        --argstr commitSha "$(git rev-parse HEAD)"
        --argstr commitDate "$(git log HEAD -1 --format=%cd)"
    - ln -s ./result/*.md .
    artifact_paths:
      - TrivialDAO.md
      - GameDAO.md
      - RegistryDAO.md
      - TreasuryDAO.md

  - label: xrefcheck generated doc
    soft_fail: true  # TODO: remove
    if: build.branch != "autodoc/master" && build.source != "schedule"
    commands:
    - mkdir tmp
    - if [ "$BUILDKITE_BRANCH" = "master" ];
      then CONTRACT_DOC_STEP="contract doc release";
      else CONTRACT_DOC_STEP="contract doc development";
      fi
    - buildkite-agent artifact download "*.md" tmp/
        --step "$$CONTRACT_DOC_STEP"
    - nix run -f ci.nix xrefcheck -c xrefcheck
        --mode local-only --root tmp

  - label: autodoc upload
    if: build.branch == "master" && build.source != "schedule"
    commands:
    - mkdir tmp
    - buildkite-agent artifact download "*.md" tmp/
        --step "contract doc release"
    - ./scripts/ci/upload-autodoc.sh

  - label: create auto prerelease
    if: build.branch == "master" && build.source != "schedule"
    commands:
      - mkdir assets
      - buildkite-agent artifact download RegistryDAO.md assets --step "contract doc release"
      - buildkite-agent artifact download TreasuryDAO.md assets --step "contract doc release"
      - buildkite-agent artifact download baseDAO.tz assets --step "build-ligo"
      - nix run -f ci.nix packages.baseDAO.exes.baseDAO -c baseDAO print --name RegistryDAO --output assets/RegistryDAO.tz
      - nix run -f ci.nix packages.baseDAO.exes.baseDAO -c baseDAO print --name TreasuryDAO --output assets/TreasuryDAO.tz
      - nix run -f ci.nix gh -c gh release delete auto-release --yes || true
      - nix run -f ci.nix pkgs.git -c git fetch && git tag -f auto-release && git push --force --tags
      - nix run -f ci.nix gh -c gh release create --prerelease auto-release --title auto-release --notes ""
      - nix run -f ci.nix gh -c gh release upload auto-release assets/*


notify:
  - email: "tezos-alerts@serokell.io"
    if: build.state == "failed" && build.source == "schedule"
